# -*- coding: utf-8 -*-
"""load_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17u1jLleesRs2zk3787Fx5qcJDQjp1b0i
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Airline_Delay_Cause.csv")

print(df.shape)
df.head()

delay_cols = [
    "carrier_delay",
    "weather_delay",
    "nas_delay",
    "security_delay",
    "late_aircraft_delay"
]

df[delay_cols] = df[delay_cols].fillna(0)

df["delay_cause"] = df[delay_cols].idxmax(axis=1)

df = df[df[delay_cols].sum(axis=1) > 0]

df["delay_cause"].value_counts()

features = [
    "year",
    "month",
    "carrier",
    "airport",
    "arr_flights",
    "arr_del15",
    "arr_cancelled",
    "arr_diverted"
]

X = df[features]
y = df["delay_cause"]

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=True
)

X_encoded = encoder.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=1000
)

model.fit(X_train, y_train)

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=model.classes_,
    yticklabels=model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Multinomial Logistic Regression – Delay Cause Classification")
plt.show()

y_prob = model.predict_proba(X_test)

prob_df = pd.DataFrame(
    y_prob,
    columns=model.classes_
)

prob_df.head()

feature_names = encoder.get_feature_names_out()

coef_df = pd.DataFrame(
    model.coef_,
    columns=feature_names,
    index=model.classes_
)

for cls in coef_df.index:
    print(f"\nTop drivers for {cls}")
    print(
        coef_df.loc[cls]
        .sort_values(key=abs, ascending=False)
        .head(8)
    )

errors = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

errors = errors[errors["Actual"] != errors["Predicted"]]

errors.head()

from sklearn.metrics import accuracy_score

class_accuracy = {}

for cls in model.classes_:
    idx = y_test == cls
    class_accuracy[cls] = accuracy_score(
        y_test[idx],
        y_pred[idx]
    )

pd.Series(class_accuracy).plot(
    kind="bar",
    title="Class-wise Prediction Accuracy",
    figsize=(8,4)
)
plt.ylabel("Accuracy")
plt.show()

from sklearn.dummy import DummyClassifier

baseline = DummyClassifier(strategy="most_frequent")
baseline.fit(X_train, y_train)

baseline_pred = baseline.predict(X_test)

print("Baseline accuracy:",
      (baseline_pred == y_test).mean())

print("Model accuracy:",
      (y_pred == y_test).mean())

prob_matrix = model.predict_proba(X_test)

prob_df = pd.DataFrame(
    prob_matrix,
    columns=model.classes_,
    index=y_test.index
)

delay_cols = [
    "carrier_delay",
    "weather_delay",
    "nas_delay",
    "security_delay",
    "late_aircraft_delay"
]

total_delay = df.loc[y_test.index, delay_cols].sum(axis=1)

expected_contrib = prob_df.multiply(
    total_delay,
    axis=0
)

expected_contrib.head()

expected_contrib.mean().sort_values().plot(
    kind="barh",
    figsize=(8,5),
    title="Expected Delay Contribution by Cause (Minutes)"
)

plt.xlabel("Expected Delay Minutes")
plt.ylabel("Delay Cause")
plt.show()